apiVersion: v1
kind: Pod
metadata:
  name: print-envars-greeting
spec: 
  containers:
  - name: print-env-container
    image: bash
    command: 
      - sh
      - "-c"
    args: 
      - echo "$(GREETING) $(COMPANY) $(GROUP)"; sleep 3600
    ports:
    - containerPort: 80
    env: 
      - name: GREETING 
        value: "Welcome to"
      - name: COMPANY
        value: "Devops"
      - name: GROUP
        value: "Industries"
