apiVersion: v1
kind: Pod
metadata:
  name: nginxready
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    readinessProbe:
      httpGet: 
        path: /health
        port: 80

