apiVersion: v1
kind: Pod
metadata:
  name: red
spec:
  initContainers:
  - name: bustybox
    image: bustybox
    command: ["sleep", "20"]
  containers:
  - name: red
    image: redis
    #command: ["sleep", "3600"]  
    ports:
    - containerPort: 80
