apiVersion: v1
kind: Pod
metadata:
  name: multicontainerpod
spec:
  containers:
  - name: lemon
    image: busybox
    #command: ["sleep", "3600"]  
  - name: gold
    image: redis
    ports:
    - containerPort: 80
